### PR TITLE
Add megaqc upload

### PR DESCRIPTION
**Pull request by jethror1**
- Adds required script to download `multiqc_data.json` files from every 002 run in DNAnexus and run megaqc upload to import to database
- Modified docker image to include dxpy requirements

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/megaqc/1)

### CODE REVIEW

**Review by chrispyatt — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/megaqc/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[megaqc_upload.py, line 73 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-MqxyGj9130apfcbZWEG:-MqxyGj9130apfcbZWEH:b-t4u0nc) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L73)):*
> ```Python
>     """
>     with open("/app/megaqc/multiqc_config.yaml", "w") as fh:
>         fh.write(f"megaqc_url: {os.environ.get('MEGAQC_URL')}\n")
> ```

should MEGAQC_URL be mentioned as a required env variable at the beginning of this file?
___
*[megaqc_upload.py, line 81 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-MqxyZ_T3SU7afBA1fSz:-MqxyZ_T3SU7afBA1fT-:b3zlsxi) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L81)):*
> ```Python
>     Multiple auth tokens are stored in the config prefixed with MEGA_TOKEN_,
>     gather all these into a dict to know which sequencer 'user' to attribute
>     to upload to for filtering later by the key being in the run name.
> ```

typo - "attribute to upload" > "attribute the upload"
___
*[megaqc_upload.py, line 294 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-Mqy4ddmCats6F5tXRnR:-Mqy4ddmCats6F5tXRnS:bv6b8l8) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L294)):*
> ```Python
> 
>                 # write multiqc config with correct token and upload
>                 create_multiqc_cfg(tokenn=seq_token)
> ```

tokenn should be token?

**Review by chrispyatt — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/megaqc/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[megaqc_upload.py, line 73 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-MqxyGj9130apfcbZWEG:-MqxyGj9130apfcbZWEH:b-t4u0nc) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L73)):*
> ```Python
>     """
>     with open("/app/megaqc/multiqc_config.yaml", "w") as fh:
>         fh.write(f"megaqc_url: {os.environ.get('MEGAQC_URL')}\n")
> ```

should MEGAQC_URL be mentioned as a required env variable at the beginning of this file?
___
*[megaqc_upload.py, line 81 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-MqxyZ_T3SU7afBA1fSz:-MqxyZ_T3SU7afBA1fT-:b3zlsxi) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L81)):*
> ```Python
>     Multiple auth tokens are stored in the config prefixed with MEGA_TOKEN_,
>     gather all these into a dict to know which sequencer 'user' to attribute
>     to upload to for filtering later by the key being in the run name.
> ```

typo - "attribute to upload" > "attribute the upload"
___
*[megaqc_upload.py, line 294 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-Mqy4ddmCats6F5tXRnR:-Mqy4ddmCats6F5tXRnS:bv6b8l8) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L294)):*
> ```Python
> 
>                 # write multiqc config with correct token and upload
>                 create_multiqc_cfg(tokenn=seq_token)
> ```

tokenn should be token?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/megaqc/1)* status: all files reviewed, 2 unresolved discussions (waiting on @chrispyatt and @mattgarner)

___
*[megaqc_upload.py, line 73 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-MqxyGj9130apfcbZWEG:-Mqyddc67zv-949m9jlh:b-896fix) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L73)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

should MEGAQC_URL be mentioned as a required env variable at the beginning of this file?
</blockquote></details>

Done.
___
*[megaqc_upload.py, line 294 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-Mqy4ddmCats6F5tXRnR:-MqydcQNAOWws6jSMnX2:b-896fix) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L294)):*
<details><summary><i>Previously, chrispyatt wrote…</i></summary><blockquote>

tokenn should be token?
</blockquote></details>

Done.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/megaqc/1)* status: all files reviewed, 4 unresolved discussions (waiting on @chrispyatt and @jethror1)

___
*[megaqc_upload.py, line 73 at r1](https://reviewable.io/reviews/eastgenomics/megaqc/1#-MqxyGj9130apfcbZWEG:-Mr1mIgM7jC5a23RO9MD:b-pjfp2y) ([raw file](https://github.com/eastgenomics/megaqc/blob/6e088917022d7ce56b6c81213a0ebe83a38a79de/megaqc_upload.py#L73)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it done? I don't see it
___
*[megaqc_upload.py, line 138 at r2](https://reviewable.io/reviews/eastgenomics/megaqc/1#-Mr1n_lH06z9B0UJsYs-:-Mr1n_lH06z9B0UJsYs0:b-ifzflk) ([raw file](https://github.com/eastgenomics/megaqc/blob/9750fd303f80da9d6517740b1ada8c466ade7cd2/megaqc_upload.py#L138)):*
> ```Python
> 
> 
> def filter_jsons(projects, jsons):
> ```

Are we handling projects with multiple jsons elsewhere?



_Code quote:_
```Python
filter_jsons
```
___
*[megaqc_upload.py, line 268 at r2](https://reviewable.io/reviews/eastgenomics/megaqc/1#-Mr1o3IiDrcUrkuSYHaV:-Mr1o3IiDrcUrkuSYHaW:bu8uspx) ([raw file](https://github.com/eastgenomics/megaqc/blob/9750fd303f80da9d6517740b1ada8c466ade7cd2/megaqc_upload.py#L268)):*
> ```Python
> 
>     for json_file, run in filtered_jsons.items():
>         if run not in " ".join(log_file) and run not in downloaded:
> ```

This relates to my earlier question - I expect that this will prevent multiple jsons per run. Are we satisfied that it will always take the first json?



_Code quote:_
```Python
if run not in " ".join(log_file) and run not in downloaded:
```

**Review by chrispyatt — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/megaqc/1)* status: all files reviewed, 3 unresolved discussions (waiting on @chrispyatt and @jethror1)

**Review by chrispyatt — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/megaqc/1)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

**Review by mattgarner — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/megaqc/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
